concurrency: 16

run:
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  exhaustive:
    default-signifies-exhaustive: true
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/zeropsio)
  gosec:
    excludes:
      - G404 # Insecure random number source (rand) - we intentionally use mathRand in some places

issues:
  max-same-issues: 0

linters:
  enable:
    - goimports # should be run before gci!
    - gci
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
#    - gocognit
    - prealloc
    - nakedret
    - gosec
    - gofmt
    - unconvert
    - exportloopref
    - exhaustive
    - asciicheck
#    - nolintlint
#    - cyclop
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - gochecknoglobals
    - nestif
#    - sqlclosecheck
#    - rowserrcheck
    - errcheck
    - bodyclose
    - gosimple
    - goconst

  disable-all: true
  fast: false
