name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    name: Build && tests for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux amd64
            os: ubuntu-latest
            osEnv: GOOS=linux GOARCH=amd64
            runLint: true
            runTests: true

          - name: darwin amd64
            os: macos-latest
            osEnv: GOOS=darwin GOARCH=amd64
            runLint: true
            runTests: true

          - name: darwin arm64
            os: macos-latest
            osEnv: GOOS=darwin GOARCH=arm64
            runLint: false
            runTests: false

          - name: windows amd64
            os: ubuntu-latest
            osEnv: GOOS=windows GOARCH=amd64
            runLint: false
            runTests: false

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ~1.22
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        export GOPATH=$HOME/go
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

    - name: Build
      run: env ${{ matrix.osEnv }} go build -v ./cmd/... ./src/...

    - name: Test
      if: ${{ matrix.runTests }}
      run: env ${{ matrix.osEnv }} make test

    - name: Lint
      if: ${{ matrix.runLint }}
      run: env ${{ matrix.osEnv }} make lint
